version: "3.8"

services:
  db:
    image: mysql:8
    container_name: mysql-user
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Oemry241995@
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

  server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-app
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
      - rabbitmq
    command: ["/app/server"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-worker
    env_file:
      - .env
    depends_on:
      - db
      - redis
      - rabbitmq
    command: ["/app/worker"]

volumes:
  mysql-data:
