services:
  server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ecommerce_app
    restart: always
    env_file:
      - .env
    ports:
      - "5003:5003"
    expose:
      - "5003"
    healthcheck:
      test:
        ["CMD-SHELL", "wget -q --spider http://localhost:5003/health || exit 1"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    networks:
      - shared-net

networks:
  shared-net:
    external: true
